name: Run Tests

on:
  push:
    branches:
      - windowsapp-tests-gha-migration
  workflow_dispatch:
    inputs:
      testSuites:
        description: 'Test suite to run'
        required: true
        default: 'All'
        type: choice
        options:
        - All
        - AnnotationsCurrentBooksTC
        - ArchivedBooksHubPageViewTC
        - BackToBoardsTC
        - BooksSyncingWithUpdatesTC
        - CalendarTC
        - ChangePasswordTC
        - CommentNotificationTC
        - CurrentBooksHubPageViewTC
        - CurrentBooksHubSyncingTC
        - ExportAnnotationsTC

jobs: 
  Prebuild:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ env.TESTS }}
    steps:
      - id: set-matrix
        run: |      
          if [ "${{ inputs.testSuites }}" == "All" ]
          then 
            echo "TESTS=("AnnotationsCurrentBooksTC" "ArchivedBooksHubPageViewTC" "BackToBoardsTC" "BooksSyncingWithUpdatesTC")" >> $GITHUB_ENV           
            echo "All"
          else
           echo "TESTS=${{ github.event.inputs.testSuites }}" >> $GITHUB_ENV
            echo "Single"
          fi

  Run_TestSuite:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJSON(needs.prebuild.outputs.tests) }}
    steps:
      - name: running
        run: echo "running job with ${{ matrix.test }}"
