name: Run Tests

on:
  push:
    branches:
      - windowsapp-tests-gha-migration
  workflow_dispatch:
    inputs:
      testSuites:
        description: 'Test suite to run'
        required: true
        default: 'All'
        type: choice
        options:
        - All
        - AnnotationsCurrentBooksTC
        - ArchivedBooksHubPageViewTC
        - BackToBoardsTC
        - BooksSyncingWithUpdatesTC
        - CalendarTC
        - ChangePasswordTC
        - CommentNotificationTC
        - CurrentBooksHubPageViewTC
        - CurrentBooksHubSyncingTC
        - ExportAnnotationsTC

jobs: 
  Prebuild:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.set-matrix.outputs.tests }}
    steps:
      - id: set-matrix
        run: |      
          if [ "${{ inputs.testSuites }}" == "All" ]
          then 
            # echo "TESTS=("AnnotationsCurrentBooksTC" "ArchivedBooksHubPageViewTC" "BackToBoardsTC" "BooksSyncingWithUpdatesTC")" >> $GITHUB_ENV           
            echo "All"
          else
            echo "::set-output name=tests::${{format('[{0}]',github.event.inputs.testSuites)}}"
            echo "Single"
          fi

  Run_TestSuite:
    needs: [ 'Prebuild' ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: ${{fromJSON(needs.Prebuild.outputs.tests)}}
    steps:
      - name: running
        run: echo "running job with ${{ matrix.test }}"
